name: 'El salón'
rules:
  - { image: fondo.png,                         when: { blue: 0, black: 0, red:   0, green: 0 } } 
  - { image: fondoConSeño.png,                  when: { blue: 0, black: 1, red:   0, green: 0 } } 
  - { image: escritorio.png,                    when: { blue: 1, black: 0, red: '*', green: 0 } } 
  - { image: escritorioConSeño.png,             when: { blue: 1, black: 1, red: '*', green: 0 } } 
  - { image: escritorioConSeñoYContraseña.png,  when: { blue: 2, black: 1, red: '*', green: 0 } } 
  - { image: escritorioConContraseña.png,       when: { blue: 2, black: 0, red: '*', green: 0 } } 
  - { image: pizarron.png,                      when: { blue: 0, black: 0, red:   0, green: 1 } } 
  - { image: pizarronConSeño.png,               when: { blue: 0, black: 1, red:   0, green: 1 } } 
  - { image: pizarronConSeñoyContraSeña1.png,   when: { blue: 0, black: 1, red:   1, green: 1 } } 
  - { image: pizarronConSeñoyContraSeña2.png,   when: { blue: 0, black: 1, red:   2, green: 1 } } 
  - { image: pizarronConSeñoyContraSeña3.png,   when: { blue: 0, black: 1, red:   3, green: 1 } } 
  - { image: pizarronConSeñoyContraSeña4.png,   when: { blue: 0, black: 1, red:   4, green: 1 } } 
  - { image: pizarronConSeñoyContraSeña5.png,   when: { blue: 0, black: 1, red:   5, green: 1 } } 
  - { image: pizarronConContraseña1.png,        when: { blue: 0, black: 0, red:   1, green: 1 } } 
  - { image: pizarronConContraseña2.png,        when: { blue: 0, black: 0, red:   2, green: 1 } } 
  - { image: pizarronConContraseña3.png,        when: { blue: 0, black: 0, red:   3, green: 1 } } 
  - { image: pizarronConContraseña4.png,        when: { blue: 0, black: 0, red:   4, green: 1 } } 
  - { image: pizarronConContraseña5.png,        when: { blue: 0, black: 0, red:   5, green: 1 } } 
